apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-data
  namespace: mysql
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.mysql.pv.storage}}
  hostPath:
    path: /data/
